### ISSUE TITLE
Erro de Documentação - Solicitar Bilhete

### ISSUE THREAD

**Issue by NickBabo** [NickBabo/Source-Code-Inspection#16]
Há um erro de omissão na pré-condição do método de solicitar bilhete, pois deveria haver a pré-condição da existência de saldo na máquina.
**Localização do Erro**: 1.3.2 CSU02 – Solicitar bilhete
Categoria: Omissão
Severidade: Alto ( sem verificação de saldo, será possível solicitar bilhetes sem pagar ).

**Comment by carloslobato03** [comment]
Adicionado pré-requisito de saldo ser necessário para conseguir solicitar o bilhete
